#!/usr/bin/env bash
set -euo pipefail

SSH_PORT="22222"
DROPIN_DIR="/etc/ssh/sshd_config.d"
DROPIN_FILE="${DROPIN_DIR}/99-custom-hardening.conf"
BACKUP_DIR="/root/ssh-config-backups"
CURRENT_USER="${SUDO_USER:-$(id -un)}"

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --port PORT        SSH port, default: 22222
  --user USER        User to check authorized_keys for, default: current sudo user
  --yes             Skip confirmation prompt
  -h, --help        Show this help

Examples:
  sudo bash $0
  sudo bash $0 --port 22222 --user ubuntu
EOF
}

YES=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)
      SSH_PORT="$2"
      shift 2
      ;;
    --user)
      CURRENT_USER="$2"
      shift 2
      ;;
    --yes)
      YES=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

need_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "Please run as root, for example:"
    echo "  sudo bash $0"
    exit 1
  fi
}

detect_sshd_service() {
  if systemctl list-unit-files 2>/dev/null | grep -q '^ssh\.service'; then
    echo "ssh"
  elif systemctl list-unit-files 2>/dev/null | grep -q '^sshd\.service'; then
    echo "sshd"
  else
    echo ""
  fi
}

get_user_home() {
  local user="$1"
  getent passwd "$user" | cut -d: -f6
}

check_authorized_keys() {
  local user="$1"
  local home
  home="$(get_user_home "$user")"

  if [[ -z "$home" || ! -d "$home" ]]; then
    echo "User '$user' does not exist or has no home directory."
    exit 1
  fi

  if [[ ! -s "$home/.ssh/authorized_keys" ]]; then
    echo
    echo "ERROR: $home/.ssh/authorized_keys is missing or empty."
    echo
    echo "Public key login may not work for user '$user'."
    echo "Add your public key first, then rerun this script."
    echo
    echo "Example:"
    echo "  mkdir -p $home/.ssh"
    echo "  nano $home/.ssh/authorized_keys"
    echo "  chown -R $user:$user $home/.ssh"
    echo "  chmod 700 $home/.ssh"
    echo "  chmod 600 $home/.ssh/authorized_keys"
    exit 1
  fi
}

backup_configs() {
  mkdir -p "$BACKUP_DIR"

  if [[ -f /etc/ssh/sshd_config ]]; then
    cp /etc/ssh/sshd_config "$BACKUP_DIR/sshd_config.bak.$(date +%F-%H%M%S)"
  fi

  if [[ -f "$DROPIN_FILE" ]]; then
    cp "$DROPIN_FILE" "$BACKUP_DIR/99-custom-hardening.conf.bak.$(date +%F-%H%M%S)"
  fi
}

ensure_include_enabled() {
  if ! grep -Eq '^[[:space:]]*Include[[:space:]]+/etc/ssh/sshd_config\.d/\*\.conf' /etc/ssh/sshd_config; then
    cp /etc/ssh/sshd_config "$BACKUP_DIR/sshd_config.before-include.$(date +%F-%H%M%S)"
    printf '\nInclude /etc/ssh/sshd_config.d/*.conf\n' >> /etc/ssh/sshd_config
  fi
}

write_dropin_config() {
  mkdir -p "$DROPIN_DIR"

  cat > "$DROPIN_FILE" <<EOF
# Generated by ssh-hardening-22222.sh
# Harden SSH access.

Port ${SSH_PORT}
Protocol 2

PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no

PermitRootLogin no
PermitEmptyPasswords no

UsePAM yes
X11Forwarding no

MaxAuthTries 3
ClientAliveInterval 300
ClientAliveCountMax 2
EOF
}

open_firewall_port() {
  local port="$1"

  if command -v ufw >/dev/null 2>&1; then
    if ufw status 2>/dev/null | grep -qi active; then
      echo "Detected active ufw, allowing ${port}/tcp ..."
      ufw allow "${port}/tcp" >/dev/null || true
    fi
  fi

  if command -v firewall-cmd >/dev/null 2>&1; then
    if firewall-cmd --state >/dev/null 2>&1; then
      echo "Detected active firewalld, allowing ${port}/tcp ..."
      firewall-cmd --permanent --add-port="${port}/tcp" >/dev/null || true
      firewall-cmd --reload >/dev/null || true
    fi
  fi

  if command -v iptables >/dev/null 2>&1; then
    if iptables -S INPUT 2>/dev/null | grep -q -- "--dport ${port}"; then
      :
    else
      echo "iptables detected. Not modifying persistent iptables rules automatically."
      echo "If your provider uses iptables manually, make sure tcp/${port} is allowed."
    fi
  fi
}

test_sshd_config() {
  if ! sshd -t; then
    echo
    echo "ERROR: sshd config test failed."
    echo "Backup directory: $BACKUP_DIR"
    echo "No restart performed."
    exit 1
  fi
}

restart_sshd() {
  local service
  service="$(detect_sshd_service)"

  if [[ -n "$service" ]]; then
    systemctl restart "$service"
  else
    service ssh restart 2>/dev/null || service sshd restart 2>/dev/null || {
      echo "Could not restart ssh/sshd service automatically."
      echo "Please restart SSH manually."
      exit 1
    }
  fi
}

show_summary() {
  echo
  echo "SSH hardening applied."
  echo
  echo "New SSH port:"
  echo "  ${SSH_PORT}"
  echo
  echo "Login policy:"
  echo "  Public key login       : enabled"
  echo "  Password login         : disabled"
  echo "  Keyboard-interactive   : disabled"
  echo "  Root login             : disabled"
  echo
  echo "Config file:"
  echo "  ${DROPIN_FILE}"
  echo
  echo "Backups:"
  echo "  ${BACKUP_DIR}"
  echo
  echo "IMPORTANT:"
  echo "  Do NOT close your current SSH session yet."
  echo "  Open a second terminal and test:"
  echo
  echo "    ssh -p ${SSH_PORT} ${CURRENT_USER}@YOUR_SERVER_IP"
  echo
  echo "If the new connection works, you can close the old session."
}

main() {
  need_root

  if [[ ! "$SSH_PORT" =~ ^[0-9]+$ || "$SSH_PORT" -lt 1 || "$SSH_PORT" -gt 65535 ]]; then
    echo "Invalid port: $SSH_PORT"
    exit 1
  fi

  if [[ ! -f /etc/ssh/sshd_config ]]; then
    echo "/etc/ssh/sshd_config not found."
    exit 1
  fi

  if ! command -v sshd >/dev/null 2>&1; then
    echo "sshd command not found."
    exit 1
  fi

  check_authorized_keys "$CURRENT_USER"

  echo
  echo "This script will:"
  echo "  - Change SSH port to ${SSH_PORT}"
  echo "  - Enable public key authentication"
  echo "  - Disable password login"
  echo "  - Disable root login"
  echo "  - Restart SSH service"
  echo
  echo "User checked for public key:"
  echo "  ${CURRENT_USER}"
  echo

  if [[ "$YES" -ne 1 ]]; then
    read -r -p "Continue? Type YES to proceed: " answer
    if [[ "$answer" != "YES" ]]; then
      echo "Cancelled."
      exit 0
    fi
  fi

  backup_configs
  ensure_include_enabled
  write_dropin_config
  open_firewall_port "$SSH_PORT"
  test_sshd_config
  restart_sshd
  show_summary
}

main "$@"
